import framesConfig from '../assets/frames/frames.json';

export interface Frame {
  id: string;
  name: string;
  file: string;
}

export interface FrameCategory {
  id: string;
  title: string;
  description: string;
  frames: Frame[];
}

class FrameService {
  private categories: FrameCategory[];

  constructor() {
    this.categories = framesConfig.categories;
  }

  /**
   * Get all frame categories
   */
  getAllCategories(): FrameCategory[] {
    return this.categories;
  }

  /**
   * Get a specific category by ID
   */
  getCategory(categoryId: string): FrameCategory | undefined {
    return this.categories.find(cat => cat.id === categoryId);
  }

  /**
   * Get frames for a specific category
   */
  getFramesForCategory(categoryId: string): Frame[] {
    const category = this.getCategory(categoryId);
    return category ? category.frames : [];
  }

  /**
   * Get the source object for a frame image
   * This converts the frame file path to a require() statement
   */
  getFrameSource(frame: Frame): any {
    // Map frame paths to actual require statements
    const framePath = frame.file;
    
    try {
      // Dynamically require the frame image
      // Note: This section is auto-generated by scripts/generate-frame-mappings.js
                      // Auto-generated frame mappings
    // To regenerate: node scripts/generate-frame-mappings.js
    switch (framePath) {

      // Birthday Party
      case 'birthday/1.png':
        return require('../assets/frames/birthday/1.png');
      case 'birthday/2.png':
        return require('../assets/frames/birthday/2.png');

      default:
        console.warn(`Frame not found: ${framePath}`);
        return null;
    }
    } catch (error) {
      console.error(`Error loading frame ${framePath}:`, error);
      return null;
    }
  }

  /**
   * Get frame by ID across all categories
   */
  getFrameById(frameId: string): Frame | undefined {
    for (const category of this.categories) {
      const frame = category.frames.find(f => f.id === frameId);
      if (frame) {
        return frame;
      }
    }
    return undefined;
  }

  /**
   * Check if a category exists
   */
  categoryExists(categoryId: string): boolean {
    return this.categories.some(cat => cat.id === categoryId);
  }
}

export const frameService = new FrameService();

